#!/usr/bin/env python3
"""Independent exact verifier for the CA(12;2,8,3) nonexistence certificate.

This implementation is intentionally different from the C++ generator:
- ternary columns are generated by decoding all 3^12 integers, not recursively;
- graph optimality is checked by Bron-Kerbosch maximal-clique enumeration,
  not fixed-size bitset enumeration;
- certificate candidate and edge files are compared against independently
  reconstructed sets.

All arithmetic and comparisons are exact integers.
"""
from __future__ import annotations

import argparse
import csv
import itertools
import json
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable, Iterator, Sequence

N = 12
V = 3
FULL = (1 << 9) - 1
PERMS = tuple(itertools.permutations(range(3)))


def transpose(m: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(m[3 * j + i] for i in range(3) for j in range(3))


def canonical_matrix(m: tuple[int, ...]) -> tuple[int, ...]:
    images: list[tuple[int, ...]] = []
    for pr in PERMS:
        for pc in PERMS:
            p = tuple(m[3 * pr[i] + pc[j]] for i in range(3) for j in range(3))
            images.append(p)
            images.append(transpose(p))
    return min(images)


def all_matrix_orbits() -> dict[tuple[int, ...], int]:
    counts: Counter[tuple[int, ...]] = Counter()
    for extras in itertools.combinations_with_replacement(range(9), 3):
        m = [1] * 9
        for q in extras:
            m[q] += 1
        counts[canonical_matrix(tuple(m))] += 1
    return dict(sorted(counts.items()))


def decode_base3(code: int, length: int = N) -> tuple[int, ...]:
    # Least significant trit is placed last. This ordering differs from the C++
    # recursive generator but yields the same canonical set after sorting.
    out = [0] * length
    for i in range(length - 1, -1, -1):
        code, out[i] = divmod(code, 3)
    return tuple(out)


def canonicalize_symbols(x: Sequence[int]) -> tuple[int, ...]:
    relabel: dict[int, int] = {}
    next_label = 0
    out: list[int] = []
    for a in x:
        if a not in relabel:
            relabel[a] = next_label
            next_label += 1
        out.append(relabel[a])
    return tuple(out)


def independently_generate_rgs() -> list[tuple[int, ...]]:
    canonical: list[tuple[int, ...]] = []
    for code in range(3 ** N):
        x = decode_base3(code)
        if len(set(x)) != 3:
            continue
        if canonicalize_symbols(x) == x:
            canonical.append(x)
    canonical.sort()
    return canonical


def base_columns(m: Sequence[int]) -> tuple[tuple[int, ...], tuple[int, ...]]:
    c0: list[int] = []
    c1: list[int] = []
    for i in range(3):
        for j in range(3):
            c0.extend([i] * m[3 * i + j])
            c1.extend([j] * m[3 * i + j])
    assert len(c0) == N and len(c1) == N
    return tuple(c0), tuple(c1)


def pair_mask(a: Sequence[int], b: Sequence[int]) -> int:
    mask = 0
    for x, y in zip(a, b, strict=True):
        mask |= 1 << (3 * x + y)
    return mask


def read_candidates(path: Path) -> list[tuple[int, ...]]:
    result: list[tuple[int, ...]] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            index_s, word = line.split()
            if int(index_s) != len(result):
                raise AssertionError(f"nonconsecutive candidate index in {path}")
            if len(word) != N or set(word) - {"0", "1", "2"}:
                raise AssertionError(f"malformed candidate in {path}: {word}")
            result.append(tuple(int(ch) for ch in word))
    return result


def read_edges(path: Path, n: int) -> set[tuple[int, int]]:
    result: set[tuple[int, int]] = set()
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            a_s, b_s = line.split()
            a, b = int(a_s), int(b_s)
            if not (0 <= a < b < n):
                raise AssertionError(f"malformed edge in {path}: {(a, b)}")
            if (a, b) in result:
                raise AssertionError(f"duplicate edge in {path}: {(a, b)}")
            result.add((a, b))
    return result


def build_edges(candidates: Sequence[Sequence[int]]) -> set[tuple[int, int]]:
    edges: set[tuple[int, int]] = set()
    for i, a in enumerate(candidates):
        for j in range(i + 1, len(candidates)):
            if pair_mask(a, candidates[j]) == FULL:
                edges.add((i, j))
    return edges


def adjacency_sets(n: int, edges: Iterable[tuple[int, int]]) -> list[set[int]]:
    adj = [set() for _ in range(n)]
    for a, b in edges:
        adj[a].add(b)
        adj[b].add(a)
    return adj


def maximal_clique_statistics(adj: Sequence[set[int]]) -> tuple[int, int, tuple[int, ...], int]:
    """Bron-Kerbosch with pivoting; returns omega, count at omega, witness, maximal count."""
    max_size = 0
    max_count = 0
    witness: tuple[int, ...] = ()
    maximal_count = 0

    sys.setrecursionlimit(max(3000, len(adj) + 100))

    def bronk(r: tuple[int, ...], p: set[int], x: set[int]) -> None:
        nonlocal max_size, max_count, witness, maximal_count
        if not p and not x:
            maximal_count += 1
            size = len(r)
            if size > max_size:
                max_size = size
                max_count = 1
                witness = tuple(sorted(r))
            elif size == max_size:
                max_count += 1
            return

        union = p | x
        pivot = max(union, key=lambda u: len(p & adj[u])) if union else None
        extension = sorted(p - (adj[pivot] if pivot is not None else set()))
        for v in extension:
            bronk(r + (v,), p & adj[v], x & adj[v])
            p.remove(v)
            x.add(v)

    bronk((), set(range(len(adj))), set())
    return max_size, max_count, witness, maximal_count


def load_patterns_csv(path: Path) -> list[tuple[tuple[int, ...], int]]:
    rows: list[tuple[tuple[int, ...], int]] = []
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for expected_id, row in enumerate(reader):
            if int(row["pattern_id"]) != expected_id:
                raise AssertionError("pattern IDs are not consecutive")
            m = tuple(int(row[f"m{i}{j}"]) for i in range(3) for j in range(3))
            rows.append((m, int(row["orbit_size"])))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", nargs="?", default=Path(__file__).resolve().parents[1], type=Path)
    args = parser.parse_args()
    root = args.root.resolve()
    cert = root / "certificate"
    started = time.perf_counter()

    summary = json.loads((cert / "lower_bound_summary.json").read_text(encoding="utf-8"))
    expected_orbits = all_matrix_orbits()
    assert sum(expected_orbits.values()) == 165
    assert len(expected_orbits) == 7

    csv_patterns = load_patterns_csv(cert / "multiplicity_patterns.csv")
    expected_patterns = list(expected_orbits.items())
    assert csv_patterns == expected_patterns, (csv_patterns, expected_patterns)
    assert summary["labelled_positive_3x3_matrices_sum_12"] == 165
    assert summary["matrix_orbits_under_S3xS3_and_transpose"] == 7

    rgs = independently_generate_rgs()
    assert len(rgs) == 86526
    assert summary["restricted_growth_columns"] == len(rgs)

    report_lines = [
        "independent_lower_bound_verifier=verify_lower_bound_independent.py",
        "generation_method=all_3^12_integer-decoded columns + Bron-Kerbosch maximal cliques",
        f"matrix_count={sum(expected_orbits.values())}",
        f"matrix_orbits={len(expected_orbits)}",
        f"canonical_columns={len(rgs)}",
    ]

    for pid, ((m, orbit_size), recorded) in enumerate(zip(expected_patterns, summary["patterns"], strict=True)):
        assert recorded["id"] == pid
        assert tuple(recorded["matrix"]) == m
        assert recorded["matrix_orbit_size"] == orbit_size

        c0, c1 = base_columns(m)
        independently_filtered = [x for x in rgs if pair_mask(c0, x) == FULL and pair_mask(c1, x) == FULL]
        recorded_candidates = read_candidates(cert / f"pattern_{pid}_candidates.txt")
        assert recorded_candidates == independently_filtered
        assert recorded["candidate_count"] == len(recorded_candidates)

        recorded_edges = read_edges(cert / f"pattern_{pid}_edges.txt", len(recorded_candidates))
        independently_built_edges = build_edges(recorded_candidates)
        assert recorded_edges == independently_built_edges
        assert recorded["edge_count"] == len(recorded_edges)

        adj = adjacency_sets(len(recorded_candidates), recorded_edges)
        omega, max_count, witness, maximal_count = maximal_clique_statistics(adj)
        assert omega == recorded["maximum_clique_size"]
        assert max_count == recorded["maximum_clique_count"]
        assert recorded["k6_count"] == 0
        assert omega < 6
        rec_w = tuple(recorded["maximum_clique_witness"])
        assert len(rec_w) == omega
        assert all((min(a, b), max(a, b)) in recorded_edges for a, b in itertools.combinations(rec_w, 2))

        report_lines.append(
            "pattern={pid} orbit={orbit} candidates={cand} edges={edges} "
            "omega={omega} maximum_cliques={mc} maximal_cliques={maximal}".format(
                pid=pid,
                orbit=orbit_size,
                cand=len(recorded_candidates),
                edges=len(recorded_edges),
                omega=omega,
                mc=max_count,
                maximal=maximal_count,
            )
        )

    elapsed = time.perf_counter() - started
    report_lines.extend([
        "conclusion=no compatibility graph contains K6",
        "lower_bound=CAN(2,8,3)>=13",
        f"elapsed_seconds={elapsed:.6f}",
        "result=PASS",
    ])
    out = "\n".join(report_lines) + "\n"
    (root / "logs" / "independent_lower_bound_verifier.log").write_text(out, encoding="utf-8")
    print(out, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
